version: "3.9"

services:
  app:
    build: .
    container_name: "nameapp_api"
    ports:
      - 3333:3333
    command: bash -c "npm run typeorm:development -- -d src/shared/infra/typeorm/index.ts migration:run && npm run dev:server"
    # command: bash -c "npm run test"
    volumes:
      - .:/user/app
  database:
    image: "postgres"
    container_name: "postgres_nameapp"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=nameapp
      - PGTZ=UTC
      - TZ=UTC
    volumes:
      - pgdata:/data/postgres
  test_database:
    image: "postgres"
    container_name: "postgres_nameapp_tests"
    restart: "always"
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=nameapp_tests
      - PGTZ=UTC
    volumes:
      - pgdata:/data/postgres
  redis:
    image: "redis:alpine"
    container_name: "redis_nameapp"
    restart: "always"
    environment:
      - REDIS_PASSWORD=dbpassword
    command: >
        --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
  test_redis:
    image: "redis:alpine"
    container_name: "redis_nameapp_tests"
    restart: "always"
    environment:
      - REDIS_PASSWORD=dbpassword
    command: >
        --requirepass ${REDIS_PASSWORD}
    ports:
      - 63791:6379
volumes:
  pgdata:
    driver: local
